module.exports = function () {
    const I = this;
    I.wait(2);
    I.fillField("First name(s)", "exec1");
    I.fillField("Last name(s)", "exec1");
    I.click("#primaryApplicantHasAlias-Yes");
    I.fillField("Enter their full name as it appears on the will", "Exec1WillName");
    I.click("#primaryApplicantIsApplying-Yes");
    I.click("//span[text()=concat('I can',\"'\", 't enter a UK postcode')]");
    I.fillField("#PostTown", "Hounslow");
    I.fillField("#County", "Middlesex");
    I.click("#otherExecutorExists-Yes");
    I.click("Add new");
    I.fillField("//input[@id='solsAdditionalExecutorList_0_additionalExecForenames']","exec2");
    I.fillField("//input[@id='solsAdditionalExecutorList_0_additionalExecLastname']","exec2");
    I.click("//input[@id='solsAdditionalExecutorList_0_additionalExecNameOnWill-No']");
    I.click("//input[@id='solsAdditionalExecutorList_0_additionalApplying-Yes']");
    I.click("//div[@id='solsAdditionalExecutorList_0_additionalExecAddress_additionalExecAddress']/span[text()=concat('I can',\"'\", 't enter a UK postcode')]");
    I.fillField("//div[@id='solsAdditionalExecutorList_0_additionalExecAddress_additionalExecAddress']//div[@id='additionalExecAddress']//input[@id='AddressLine1']", "120 Sutton Lane");
    I.fillField("//div[@id='solsAdditionalExecutorList_0_additionalExecAddress_additionalExecAddress']//div[@id='additionalExecAddress']//input[@id='PostCode']", "TW3 3DB");
    I.click("Continue");
};