const helper = require('test/end-to-end/helpers/Utils.js');
module.exports = function () {
    const I = this;
    I.wait(2);
    I.click("Go");
    I.wait(3);
    I.click("Continue");
    I.wait(4);
    I.click("Submit");
    I.wait(4);
    I.see("Ready for examination");
    I.wait(4);
    I.click("Notifications");
    I.wait(1);
    I.see("Do you wish to send an email notification for documents received?");
    I.see("Yes");
    I.click("Go");
    I.wait(4);
    I.click("Submit");
    I.wait(4);
    I.see("Examining");
    I.selectOption("Next step","Stop case");
    I.click("Go");
    I.wait(3);
    I.click("Add new");
    I.wait(1);
    I.selectOption("Select a reason for stopping the case","Deceased Name");
    I.wait(3);
    I.click("Continue");
    I.wait(7);
    I.click("Submit");
    I.wait(4);
    I.see("Case stopped");
    I.selectOption("Next step","Resolve stop");
    I.click("Go");
    I.wait(4);
    I.click("Submit");
    I.wait(4);
    I.see("Examining");
    I.wait(2);
    I.click("Stop details");
    I.wait(2);
    I.see("Deceased Name");
    I.selectOption("Next step","Mark as ready to issue");
    I.click("Go");
    I.wait(4);
    I.click("Submit");
    I.wait(4);
    I.see("Ready to issue");
    I.selectOption("Next step","Issue grant");
    I.click("Go");
    I.wait(4);
    I.click("Continue");
    I.wait(4);
    I.click("Submit");
    I.wait(4);
    I.see("Grant issued");
    I.click("Notifications");
    I.wait(1);
    I.see("Do you wish to send an email notification for documents received?");
    I.see("Yes");
    I.see("Do you wish to send an email notification for grant issued?");
    I.see("Yes");
};